- name: configuring the catalogue service
  hosts: catalogue
  become: yes
  tasks:

  - name: Enable nodejs 20 version
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: Create catalogue system user
    ansible.builtin.user:
      name: roboshop
      system: yes
      home: /app
      shell: /sbin/nologin

    
  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent    

  - name: Create the app directory
    ansible.builtin.file:
      path: /app
      state: directory     

  - name: delete catalogue zip file
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent     

  - name: Download the Catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip  

  - name: unzip the catalogue zip file which is located at /tmp/catalogue.zip 
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip 
      dest: /app
      remote_src: yes

  - name: Install npm dependency
    community.general.npm:
      path: /app    

  - name: copy the service file into /etc folder
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service    

  
  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present

  - name: Check catalogue products data
    ansible.builtin.command: >
      mongosh --host "{{ MONGODB_HOST }}" --quiet
      --eval 'db.getSiblingDB("catalogue").products.findOne() != null'
    register: catalogue_output
    changed_when: false

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: Load catalogue products
    ansible.builtin.shell: >
      mongosh --host "{{ MONGODB_HOST }}" < /app/db/master-data.js
    when: catalogue_output.stdout | trim != "true"

  - name: start catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes    