- name: This playbook creates EC2 instances and updates Route53 records
  hosts: localhost
  connection: local
  become: false

  vars:
    ami_id: "ami-0220d79f3f480ecf5"
    sg_id: "sg-019f25a2463a096b9"
    env: dev
    instances:
      - mongodb
      - catalogue

  tasks:
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        instance_type: t3.micro
        image_id: "{{ ami_id }}"
        wait: true
        security_group: "{{ sg_id }}"
        name: "{{ item }}-{{ env }}"
        tags:
          Project: roboshop
          Environment: "{{ env }}"
          Component: "{{ item }}"
          Name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}"
      register: ec2_info

    - name: Print EC2 output
      ansible.builtin.debug:
        msg: "{{ ec2_info }}"
